ALTER TABLE rooms ADD COLUMN IF NOT EXISTS collection_id TEXT NOT NULL DEFAULT '3749034386';
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS vote_round INTEGER NOT NULL DEFAULT 1;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS round_finished BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE room_members ADD COLUMN IF NOT EXISTS creator_id TEXT;

CREATE TABLE IF NOT EXISTS room_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  creator_id TEXT,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(room_id, nickname)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'room_members_room_id_nickname_key'
  ) THEN
    ALTER TABLE room_members ADD CONSTRAINT room_members_room_id_nickname_key UNIQUE(room_id, nickname);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS workshop_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id TEXT NOT NULL,
  item_id TEXT NOT NULL,
  title TEXT NOT NULL,
  preview_url TEXT,
  cached_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(collection_id, item_id)
);

CREATE TABLE IF NOT EXISTS votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  round INTEGER NOT NULL,
  nickname TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item_title TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(room_id, round, nickname)
);
